name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create profile folder
        run: mkdir -p profile

      - name: Download stats
        run: |
          curl -o profile/stats.svg "https://github-readme-stats.vercel.app/api?username=hugpaim&show_icons=true&theme=dark"

      - name: Download top langs
        run: |
          curl -o profile/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=hugpaim&layout=compact&theme=dark"

      - name: Commit files
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hugpaim/hugpaim.git
          git push origin main --force
